import { create } from 'zustand';
import { v4 as uuidv4 } from 'uuid';
import type { RecordedInteraction } from '@/components/DevicePreview';
import { sessionLogger } from '@/lib/session-logger';

export type MaestroAction = 'assertVisible' | 'tapOn' | 'inputText' | 'scroll' | 'swipe' | 'back' | 'hideKeyboard' | 'waitForAnimationToEnd' | 'launchApp';

export interface RecordedStep {
    id: string;
    num: number;
    action: MaestroAction;
    elementId: string;
    value: string;
    direction?: 'UP' | 'DOWN' | 'LEFT' | 'RIGHT';
    description: string;
    x: number;
    y: number;
    endX?: number;
    endY?: number;
    duration: number;
    timestamp: number;
    screenshotUrl?: string;
    elementInfo?: {
        resource_id?: string;
        text?: string;
        content_desc?: string;
        class_name?: string;
    };
    isPassword?: boolean;
    maestro_command?: string;
    screen_name?: string;
    fromScan?: boolean;
    autoGenerated?: boolean;
    is_focusable?: boolean;
    /** Execution status for step highlight during test run */
    execStatus?: 'idle' | 'running' | 'passed' | 'failed';
    execError?: string;
}

/** Step payload received from daemon SSE stream. */
export interface DaemonStep {
    action: string;
    elementId?: string;
    value?: string;
    direction?: string;
    maestro_command?: string;
    screen_name?: string;
    is_focusable?: boolean;
    is_pending?: boolean;   // true for inputText awaiting text confirmation
    auto_generated?: boolean;
    fallback?: boolean;
    step_index?: number;
    updated?: boolean;      // true when confirm-input updates an existing step
    x?: number;
    y?: number;
}

interface RecordingState {
    isRecording: boolean;
    recordedSteps: RecordedStep[];
    startTime: number | null;
    elapsedSeconds: number;
    deviceResolution: { width: number; height: number } | null;
    showSaveModal: boolean;
    testId: string | null;

    startRecording: (resolution?: { width: number; height: number }, testId?: string) => void;
    stopRecording: () => void;
    /** Add a step received from the daemon SSE stream. */
    addStepFromDaemon: (daemonStep: DaemonStep) => RecordedStep | null;
    /** Update an existing step by index (used for confirm-input). */
    updateStepAtIndex: (stepIndex: number, daemonStep: DaemonStep) => void;
    /** Resolve a pending inputText step by its stable id with the typed text.
     *  Id-based (not index-based) so it survives the leading launchApp step and
     *  any drag-reordering, which would otherwise misalign daemon vs. frontend
     *  indices and leave the value stuck at "__PENDING_INPUT__". */
    resolvePendingInput: (stepId: string, text: string) => void;
    addInteraction: (interaction: RecordedInteraction) => RecordedStep;
    addKeyevent: (keycode: number) => void;
    addTextInput: (text: string) => void;
    addAssertVisible: (elementId: string, autoGenerated?: boolean) => void;
    /** Insert a `launchApp` step at the start of the recording. Idempotent —
     *  if the first step is already launchApp, replaces it with the new appId
     *  (lets the user reopen the config modal without duplicating). */
    addLaunchAppStep: (appId: string, clearState: boolean) => void;
    /** Reorder a step from one index to another (drag-and-drop during recording).
     *  Re-numbers `num` so the panel stays 1..N. */
    reorderSteps: (fromIndex: number, toIndex: number) => void;
    /** Remove a recorded step by id (in case user wants to drop a noisy tap mid-recording). */
    removeStep: (id: string) => void;
    updateStepDescription: (stepId: string, description: string) => void;
    updateStepElement: (stepId: string, elementInfo: RecordedStep['elementInfo'], extra?: {
        maestro_command?: string;
        screen_name?: string;
        fromScan?: boolean;
        elementId?: string;
        maestro_action?: string;
        is_focusable?: boolean;
    }) => void;
    updateStepExecStatus: (stepIndex: number, status: RecordedStep['execStatus'], error?: string) => void;
    resetExecStatus: () => void;
    setElapsedSeconds: (seconds: number) => void;
    setShowSaveModal: (show: boolean) => void;
    clearRecording: () => void;
    restoreDraft: (testId: string) => boolean;
}

function getSwipeDirection(startX: number, startY: number, endX: number, endY: number): 'UP' | 'DOWN' | 'LEFT' | 'RIGHT' {
    const dx = endX - startX;
    const dy = endY - startY;
    if (Math.abs(dx) > Math.abs(dy)) {
        return dx > 0 ? 'RIGHT' : 'LEFT';
    }
    return dy > 0 ? 'DOWN' : 'UP';
}

function saveDraft(testId: string | null, steps: RecordedStep[]) {
    if (!testId || steps.length === 0) return;
    try {
        localStorage.setItem(`draft_steps_${testId}`, JSON.stringify(steps));
    } catch { /* localStorage full or unavailable */ }
}

function clearDraft(testId: string | null) {
    if (!testId) return;
    try {
        localStorage.removeItem(`draft_steps_${testId}`);
    } catch { /* ignore */ }
}

export const useRecordingStore = create<RecordingState>((set, get) => ({
    isRecording: false,
    recordedSteps: [],
    startTime: null,
    elapsedSeconds: 0,
    deviceResolution: null,
    showSaveModal: false,
    testId: null,

    startRecording: (resolution, testId) => {
        sessionLogger.logRecordingStart('active-device');
        set({
            isRecording: true,
            recordedSteps: [],
            startTime: Date.now(),
            elapsedSeconds: 0,
            deviceResolution: resolution || null,
            showSaveModal: false,
            testId: testId || `rec_${Date.now()}`,
        });
    },

    stopRecording: () => {
        const stepCount = get().recordedSteps.length;
        sessionLogger.logRecordingStop(stepCount);
        set({ isRecording: false, showSaveModal: true });
    },

    addStepFromDaemon: (daemonStep) => {
        const state = get();
        const num = state.recordedSteps.length + 1;
        const action = daemonStep.action as MaestroAction;

        let description = '';
        switch (action) {
            case 'assertVisible':
                description = `Confirmar tela › ${daemonStep.elementId || '?'}`;
                break;
            case 'tapOn':
                description = `Tocar em › ${daemonStep.elementId || '?'}`;
                break;
            case 'inputText':
                description = daemonStep.is_pending
                    ? 'Digitar › [aguardando texto...]'
                    : `Digitar › "${daemonStep.value || ''}"`;
                break;
            case 'scroll':
                description = `Rolar tela ${daemonStep.direction || ''}`;
                break;
            case 'swipe':
                description = `Deslizar ${daemonStep.direction || ''}`;
                break;
            default:
                description = `${action} ${daemonStep.elementId || ''}`;
        }

        const step: RecordedStep = {
            id: uuidv4(),
            num,
            action,
            elementId: daemonStep.elementId || '',
            value: daemonStep.value || '',
            direction: daemonStep.direction as RecordedStep['direction'],
            description,
            x: daemonStep.x || 0,
            y: daemonStep.y || 0,
            duration: 0,
            timestamp: Date.now(),
            maestro_command: daemonStep.maestro_command,
            screen_name: daemonStep.screen_name,
            is_focusable: daemonStep.is_focusable,
            autoGenerated: daemonStep.auto_generated,
            fromScan: !daemonStep.fallback,
        };

        const newSteps = [...state.recordedSteps, step];
        set({ recordedSteps: newSteps });
        saveDraft(state.testId, newSteps);
        return step;
    },

    updateStepAtIndex: (stepIndex, daemonStep) => {
        set(state => {
            const steps = [...state.recordedSteps];
            const existing = steps[stepIndex];
            if (!existing) return state;
            steps[stepIndex] = {
                ...existing,
                value: daemonStep.value ?? existing.value,
                maestro_command: daemonStep.maestro_command ?? existing.maestro_command,
                description: daemonStep.value
                    ? `Digitar › "${daemonStep.value}"`
                    : existing.description,
            };
            saveDraft(state.testId, steps);
            return { recordedSteps: steps };
        });
    },

    resolvePendingInput: (stepId, text) => {
        set(state => {
            const steps = state.recordedSteps.map(s => {
                if (s.id !== stepId) return s;
                const isPassword = s.isPassword
                    || s.elementId?.toLowerCase().includes('password')
                    || s.elementId?.toLowerCase().includes('senha');
                return {
                    ...s,
                    value: text,
                    isPassword,
                    maestro_command: `- inputText: "${text}"`,
                    description: isPassword
                        ? `Digitar › "${'*'.repeat(text.length)}"`
                        : `Digitar › "${text}"`,
                };
            });
            saveDraft(state.testId, steps);
            return { recordedSteps: steps };
        });
    },

    addInteraction: (interaction) => {
        const state = get();
        const num = state.recordedSteps.length + 1;

        let action: MaestroAction = 'tapOn';
        let elementId = `${interaction.startX},${interaction.startY}`;
        let description = '';
        let direction: RecordedStep['direction'] = undefined;

        if (interaction.type === 'tap') {
            action = 'tapOn';
            description = `Tocar em › (${interaction.startX}, ${interaction.startY})`;
        } else if (interaction.type === 'swipe') {
            action = 'swipe';
            direction = getSwipeDirection(
                interaction.startX, interaction.startY,
                interaction.endX || interaction.startX,
                interaction.endY || interaction.startY
            );
            elementId = '';
            description = `Deslizar ${direction}`;
        }

        const step: RecordedStep = {
            id: uuidv4(),
            num,
            action,
            elementId,
            value: action === 'swipe' ? (direction || '') : '',
            direction,
            description,
            x: interaction.startX,
            y: interaction.startY,
            endX: interaction.endX,
            endY: interaction.endY,
            duration: interaction.duration,
            timestamp: interaction.timestamp,
            maestro_command: action === 'swipe'
                ? `- swipe:\n    direction: ${direction}`
                : undefined,
        };

        const newSteps = [...state.recordedSteps, step];
        set({ recordedSteps: newSteps });
        saveDraft(state.testId, newSteps);
        return step;
    },

    addKeyevent: (keycode) => {
        const state = get();
        if (!state.isRecording) return;

        const num = state.recordedSteps.length + 1;
        let action: MaestroAction = 'back';
        let description = '';

        if (keycode === 4) {
            action = 'back';
            description = 'Voltar';
        } else if (keycode === 3) {
            action = 'back';
            description = 'Home';
        } else {
            description = `Keyevent ${keycode}`;
        }

        const step: RecordedStep = {
            id: uuidv4(),
            num,
            action,
            elementId: '',
            value: String(keycode),
            description,
            x: 0,
            y: 0,
            duration: 0,
            timestamp: Date.now(),
            maestro_command: action === 'back' ? '- pressKey: Back' : undefined,
        };

        const newSteps = [...state.recordedSteps, step];
        set({ recordedSteps: newSteps });
        saveDraft(state.testId, newSteps);
    },

    addTextInput: (text) => {
        const state = get();
        if (!state.isRecording) return;

        const steps = [...state.recordedSteps];
        const lastStep = steps[steps.length - 1];
        if (lastStep && lastStep.action === 'tapOn') {
            const num = steps.length + 1;
            const isPassword = lastStep.elementInfo?.class_name?.includes('password') ||
                lastStep.elementId?.toLowerCase().includes('password') ||
                lastStep.elementId?.toLowerCase().includes('senha');

            const step: RecordedStep = {
                id: uuidv4(),
                num,
                action: 'inputText',
                elementId: lastStep.elementId,
                value: text,
                description: isPassword ? `Digitar › "${'*'.repeat(text.length)}"` : `Digitar › "${text}"`,
                x: lastStep.x,
                y: lastStep.y,
                duration: 0,
                timestamp: Date.now(),
                isPassword,
                maestro_command: `- inputText: "${text}"`,
            };
            const newSteps = [...steps, step];
            set({ recordedSteps: newSteps });
            saveDraft(state.testId, newSteps);
        }
    },

    addAssertVisible: (elementId, autoGenerated = true) => {
        const state = get();
        const num = state.recordedSteps.length + 1;

        const step: RecordedStep = {
            id: uuidv4(),
            num,
            action: 'assertVisible',
            elementId,
            value: '',
            description: `Confirmar tela › ${elementId}`,
            x: 0,
            y: 0,
            duration: 0,
            timestamp: Date.now(),
            autoGenerated,
            maestro_command: `- assertVisible:\n    id: "${elementId}"`,
        };

        const newSteps = [...state.recordedSteps, step];
        set({ recordedSteps: newSteps });
        saveDraft(state.testId, newSteps);
    },

    reorderSteps: (fromIndex, toIndex) => {
        set(state => {
            if (
                fromIndex < 0 || toIndex < 0 ||
                fromIndex >= state.recordedSteps.length ||
                toIndex >= state.recordedSteps.length ||
                fromIndex === toIndex
            ) {
                return {};
            }
            const next = [...state.recordedSteps];
            const [moved] = next.splice(fromIndex, 1);
            next.splice(toIndex, 0, moved);
            const renumbered = next.map((s, idx) => ({ ...s, num: idx + 1 }));
            saveDraft(state.testId, renumbered);
            return { recordedSteps: renumbered };
        });
    },

    removeStep: (id) => {
        set(state => {
            const next = state.recordedSteps
                .filter(s => s.id !== id)
                .map((s, idx) => ({ ...s, num: idx + 1 }));
            saveDraft(state.testId, next);
            return { recordedSteps: next };
        });
    },

    addLaunchAppStep: (appId, clearState) => {
        const state = get();
        // Idempotent: if step #1 is already a launchApp (e.g. user reopened
        // the config modal), replace it instead of stacking.
        const head = state.recordedSteps[0];
        const isHeadLaunch = head?.action === 'launchApp';

        const description = clearState ? `Abrir app (${appId}) com clearState` : `Abrir app (${appId})`;
        const maestroCommand = clearState
            ? `- launchApp:\n    clearState: true`
            : `- launchApp`;

        const launchStep: RecordedStep = {
            id: isHeadLaunch ? head!.id : uuidv4(),
            num: 1,
            action: 'launchApp',
            elementId: appId,
            value: clearState ? 'true' : '',
            description,
            x: 0,
            y: 0,
            duration: 0,
            timestamp: Date.now(),
            autoGenerated: true,
            maestro_command: maestroCommand,
        };

        const rest = isHeadLaunch ? state.recordedSteps.slice(1) : state.recordedSteps;
        // Re-number subsequent steps so they start at 2.
        const renumbered = rest.map((s, idx) => ({ ...s, num: idx + 2 }));
        const newSteps = [launchStep, ...renumbered];
        set({ recordedSteps: newSteps });
        saveDraft(state.testId, newSteps);
    },

    updateStepDescription: (stepId, description) => {
        set(state => ({
            recordedSteps: state.recordedSteps.map(s =>
                s.id === stepId ? { ...s, description } : s
            ),
        }));
    },

    updateStepElement: (stepId, elementInfo, extra) => {
        const state = get();
        const newSteps = state.recordedSteps.map(s => {
            if (s.id !== stepId) return s;

            // Resolve the best element ID from enrichment
            let newElementId = s.elementId;
            if (extra?.elementId) {
                newElementId = extra.elementId;
            } else if (elementInfo) {
                const rid = elementInfo.resource_id;
                if (rid && !rid.startsWith('android:id')) {
                    newElementId = rid.includes('/') ? rid.split('/').pop()! : rid;
                } else if (elementInfo.text) {
                    newElementId = elementInfo.text;
                } else if (elementInfo.content_desc) {
                    newElementId = elementInfo.content_desc;
                }
            }

            // Build description based on action and element
            let description = s.description;
            if (s.action === 'tapOn') {
                description = `Tocar em › ${newElementId}`;
            } else if (s.action === 'inputText') {
                description = s.isPassword
                    ? `Digitar › "${'*'.repeat(s.value.length)}"`
                    : `Digitar › "${s.value}"`;
            }

            // Build maestro command
            let maestroCmd = extra?.maestro_command || s.maestro_command;
            if (!maestroCmd && newElementId && s.action === 'tapOn') {
                // Auto-generate if not from scan
                const isId = elementInfo?.resource_id && !elementInfo.resource_id.startsWith('android:id');
                if (isId) {
                    maestroCmd = `- tapOn:\n    id: "${newElementId}"`;
                } else {
                    maestroCmd = `- tapOn: "${newElementId}"`;
                }
            }

            return {
                ...s,
                elementId: newElementId,
                elementInfo,
                description,
                maestro_command: maestroCmd,
                is_focusable: extra?.is_focusable ?? s.is_focusable,
                ...(extra?.screen_name && { screen_name: extra.screen_name }),
                ...(extra?.fromScan !== undefined && { fromScan: extra.fromScan }),
            };
        });

        set({ recordedSteps: newSteps });
        saveDraft(state.testId, newSteps);
    },

    updateStepExecStatus: (stepIndex, status, error) => {
        set(state => ({
            recordedSteps: state.recordedSteps.map((s, i) =>
                i === stepIndex ? { ...s, execStatus: status, execError: error } : s
            ),
        }));
    },

    resetExecStatus: () => {
        set(state => ({
            recordedSteps: state.recordedSteps.map(s => ({ ...s, execStatus: 'idle', execError: undefined })),
        }));
    },

    setElapsedSeconds: (seconds) => set({ elapsedSeconds: seconds }),
    setShowSaveModal: (show) => set({ showSaveModal: show }),

    clearRecording: () => {
        const testId = get().testId;
        clearDraft(testId);
        set({
            isRecording: false,
            recordedSteps: [],
            startTime: null,
            elapsedSeconds: 0,
            showSaveModal: false,
            testId: null,
        });
    },

    restoreDraft: (testId: string) => {
        try {
            const raw = localStorage.getItem(`draft_steps_${testId}`);
            if (raw) {
                const steps = JSON.parse(raw) as RecordedStep[];
                if (steps.length > 0) {
                    set({ recordedSteps: steps, testId });
                    return true;
                }
            }
        } catch { /* corrupted data */ }
        return false;
    },
}));
